export default [
  {
    title: 'Patrick Roger',
    image: require('../../assets/patrick.png'),
    subtitle: 'Chocolates',
    address: '108 boulevard Saint Germain 75006 Paris',
    lat: '48.851971',
    long: '2.341890',
    opened: 'Monday: 10AM - 7:30PM\nTuesday: 10AM - 7:30PM\nWednesday: 10AM - 7:30PM\nThursday: 10AM - 7:30PM\nFriday: 10AM - 7:30PM\nSaturday: 10AM - 7:30PM\nSunday: 10AM - 7:30PM',
    description: 'The world of Patrick Roger is a world of surprise and passion. This artist, winner of the Meilleur Ouvrier de France loves the best products and fine chocolates. A stop at one of his shops to enjoy the fruits of his labor is a must if you are in Paris',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Pierre Hermé',
    image: require('../../assets/herme.png'),
    subtitle: 'Chocolates, Pastries, Macaroons',
    address: '72 rue Bonaparte 75006 Paris',
    lat: '48.851435',
    long: '2.332887',
    opened: 'Monday: 10AM - 7PM\nTuesday: 10AM - 7PM\nWednesday: 10AM - 7PM\nThursday: 10AM-7:30PM\nFriday: 10AM-7:30PM\nSaturday: 10AM - 8PM\nSunday: 10AM - 7PM',
    description: 'Pierre Hermé might just be able to claim the title of world\'s most acclaimed living pastry chef. Especially lauded for his always-creative, perfectly textured macarons-- those light, airy pastries made with almonds, sugar, and ganache or cream filling that should not be conflated with coconut cookies of a similar name-- Hermé has been called "the Picasso of pastry" by Vogue magazine. Britain\'s Observer magazine once deemed his chocolate cake one of the "fifty best things to eat in the world". He has also, of course, won legions of foodie devotees, and aspiring pastry chefs who cite his name when explaining why they took up the trade',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Chocolat Alain Ducasse',
    image: require('../../assets/ducasse.png'),
    subtitle: 'Chocolates, Pralines, Truffles',
    address: '40 rue de la Roquette 75011 Paris',
    lat: '48.854401',
    long: '2.372199',
    opened: 'Monday: Closed\nTuesday: 10:30AM - 7PM\nWednesday: 10:30AM - 7PM\nThursday: 10:30AM-7:30PM\nFriday: 10:30AM-7:30PM\nSaturday: 10:30AM - 8PM\nSunday: Closed',
    description: 'Alain Ducasse chocolates are available in three large families: ganaches, pralinés and truffles. Each one offering different recipes and textures, different flavours to discover. From the more traditional creations to the most surprising blends, our chocolates all have in common the highest quality ingredients and a flavour that is both rich and subtle.',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Pierre Marcolini',
    image: require('../../assets/marcolini.png'),
    subtitle: 'Chocolates, Macaroons',
    address: '3 Rue Scribe 75009 Paris',
    lat: '48.870957',
    long: '2.329907',
    opened: 'Monday: 10AM - 7PM\nTuesday: 10AM - 7PM\nWednesday: 10AM - 7PM\nThursday: 10AM-7PM\nFriday: 10AM-7PM\nSaturday: 10AM - 7:30PM\nSunday: Closed',
    description: 'A journey into the very heart of the cocoa bean\'s origins to discover the refined world and handcraft of Maison Pierre Marcolini. Discover a collection of iconic chocolate assortments that will send you on a journey into the world of Haute Chocolaterie',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
];
