export default [
  {
    title: 'Noglu',
    image: require('../../assets/noglu.png'),
    subtitle: 'Organic',
    address: '16, passage des Panoramas 75002 Paris',
    opened: 'Monday: Noon - 2:30PM\nTuesday: Noon - 2:30PM & 7:30PM - 10PM\nWednesday: Noon - 2:30PM & 7:30PM - 10PM\nThursday: Noon - 2:30PM & 7:30PM - 10PM\nFriday: Noon - 2:30PM & 7:30PM - 10PM\nSaturday: 11AM - 3PM & 7:30PM - 10PM\nSunday: Closed',
    description: 'The capital’s gluten-free and almost 100% organic pastry shop is cool and never preachy. The Noglu restaurant and its recent épicerie-take-away add-on are directly across from each other in the Passage des Panoramas. At the first one: pizzas, burgers, lasagna and pasta gratins…. At the other: Béton honey, stylish infusions and gluten-free pasta from Dove’s Farm stocked on the light wood shelves, or sandwiches (made on rice, chickpea, tapioca and potato flour bread), chilled tomato soup, fennel-pink radish-cucumber-chervil-pineapple salad, and cakes, madeleines, brownies or seasonal fruit tartelettes in the window display/bar',
    price: 'From 16€ to 35€',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: '42 Degrés',
    image: require('../../assets/degres.png'),
    subtitle: 'Raw Food',
    address: '109 Rue du Faubourg Poissonnière, 75009 Paris',
    opened: 'Monday: Noon - 2:30PM & 7PM - 10:30PM\nTuesday: Noon - 2:30PM & 7PM - 10:30PM\nWednesday: Noon - 2:30PM & 7PM - 10:30PM\nThursday: Noon - 2:30PM & 7PM - 10:30PM\nFriday: Noon - 2:30PM & 7PM - 10:30PM\nSaturday: Noon - 4PM & 7PM - 10:30PM\nSunday: Noon - 2:30PM & 7PM - 10:30PM',
    description: 'Come in and discover Raw Food ! Our restaurant is the only one to offer a 100% raw, vegan, organic menu card. Almost all of our dishes are gluten-free. An innovative, nutritious, and above all exquisite cuisine',
    price: 'Menus from 16€ to 35€',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'Café Pinson',
    image: require('../../assets/pinson.png'),
    subtitle: 'Organic',
    address: '58 rue du Faubourg Poissonniere, 75010 Paris',
    opened: 'Monday: 9AM - 12AM\nTuesday: 9AM - 12AM\nWednesday: 9AM - 12AM\nThursday: 9AM - 12AM\nFriday: 9AM - 12AM\nSaturday: 10AM - 12AM\nSunday: 10AM - 6PM',
    description: 'Café PINSON is a juice bar / café / restaurant offering healthy organic food. It was founded by Agathe, passionate about healthy living and gourmet organic food. She is the founder of the Blog LaMinutePapillon.net, and food Author (SuperJus) Healthy : Superfood (Kale, chia, spirulin, sprouts..), fresh juices, raw food (raw cacao)..Vegetarian, Vegan friendly // 100% organic // Wheat-free // Dairy-free.Home-made food, with seasonal and high quality ingredients',
    price: 'From 16€ to 35€',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'Nous Restaurant',
    image: require('../../assets/nous.png'),
    subtitle: 'French Modern',
    address: '8 Rue de Châteaudun, 75009 Paris',
    opened: 'Everyday: Noon - 2:30PM & 7PM - 10:30PM',
    description: 'Nous is a modern casual restaurant. We do good healthy street food with homemade recipes from fresh and organic products. The atsmosphere is very pleasant with very good music',
    price: 'From 16€ to 35€',
    price_tag: '€',
    reservation: true,
  },
];
