export default [
  {
    title: 'Ladurée',
    image: require('../../assets/laduree.png'),
    subtitle: 'Macaroons',
    address: '75 Avenue des Champs-Elysees, 75008 Paris',
    opened: 'Monday: 7:30AM - 11:30PM\nTuesday: 7:30AM - 11:30PM\nWednesday: 7:30AM - 11:30PM\nThursday: 7:30AM - 11:30PM\nFriday: 7:30AM - 12:30AM\nSaturday: 8:30AM - 12:30AM\nSunday: 8:30AM - 11:30AM',
    description: 'Ladurée is to pastry and macaroons what Mozart is to music: indispensable. David Holder, Chairman of Ladurée and his father Francis Holder, founder of Holder Group opened in September 1997 a new Ladurée at 75 Avenue des Champs Elysees, recreating the refined atmosphere of the Rue Royale in one place, a symbol of "the art of French living." You will be fascinated by this timeless hotel of the style of Napoleon III, a refined and authentic place located on the most beautiful avenue in the world. On the ground floor, the ", the glass "Eiffel" and terrace have a showcase on the Champs Elysees. On the first floor a series of rooms dedicated to the muses of the time "Paeva", "Castiglione", "Matilda" as well as the Library and the Chocolate which offer different atmospheres reconstituted in the Second Empire style by the decorator Jacques',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Gâteaux Thoumieux',
    image: require('../../assets/thoumieux.png'),
    subtitle: 'Cakes and Tarts',
    address: '58 rue Saint Dominique, 75007 Paris, France',
    opened: 'Monday: 10AM - 8PM\nTuesday: 10AM - 8PM\nWednesday: 10AM - 8PM\nThursday: 10AM - 8PM\nFriday: 10AM - 8PM\nSaturday: 10AM - 8PM\nSunday: 8:30AM - 5PM',
    description: 'Jean François Piège has opened a new shop in Paris, in the 7th arrondissement, and we\'re crazy about it! Just a stone\'s throw from his restaurants, you might want to try his Kouign-Amann, Saint-Dominique or the fabulous Chou Chou. To design the place, Jean François Piège asked talented interior architect and designer India Madhavi. For Gateaux Thoumieux, she went for a boudoir decor, with pastel colors. A modern and elegant decor with soft green, marble and oak',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Patisserie Cyril Lignac',
    image: require('../../assets/lignac.png'),
    subtitle: 'Cakes and Tarts',
    address: '2 rue de Chaillot, 75116 Paris, France',
    opened: 'Everyday: 7AM - 8PM',
    description: 'Highly media praised Chef Cyril Lignac teamed with pastry chef Benoît Couvrand, offers a range of bread, pastries and cakes in his shop on the lively rue Paul Bert (opposite his restaurant the Chardenoux), where you can enjoy the signature creation \'Equinoxe\' and the classics of patisserie (eclairs, rum babas, lemon tarts, etc.) revisited by the food-loving duo',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'L\'eclaire de genie',
    image: require('../../assets/eclair.png'),
    subtitle: 'Eclairs',
    address: '14 Rue Pavee, 75004 Paris',
    opened: 'Everyday: 11AM - 7:30PM',
    description: 'The French have a deep and long-running love affair with their éclairs, and no wonder. It\'s a classic French treat adored by Parisians since the 19th century, it\'s iced and stuffed with cream, and it\'s delicious. But in a fast-paced culinary world replete with "sexier," globally influenced sweets—think pastel colored macaroons, trendy cronuts, fruity brûlées—the éclair seems almost antiquated, dull, and heavy. How can this traditional French dessert keep up with the 21st century? It will be yours to find out!',
    price: 'Packs from 10€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
];
