export default [
  {
    title: 'Clamato',
    image: require('../../assets/clamato.png'),
    subtitle: 'Fish and Shellfish',
    address: '80, rue de Charonne 75011 Paris',
    opened: 'From 7pm to 11pm (nonstop from noon to 11pm Saturday and Sunday)\nClosed Monday and Tuesday.',
    description: 'Always ranked at the top of the foodosphere’s “eat-lists,” the pied-à-mer bistro of Bertrand Grébaut and Théo Pourriat, who also run Septime next door, brings a breath of fresh air to the seafood experience with their elegant dishes that taste of the sea, served in a barebones setting (a deep dining room, a long bar, wooden planks on the ceiling, carefully chosen vintage furniture), complete with beautiful marinades and raw surprises. That evening, it all began with mackerel, mirabelle plums, savory leaves and pumpkin seeds; then grey sea bream drizzled in tagete oil with tart wild blackberries; before a string of hot dishes (the famous crab fritters with a huankaina sauce; beautiful Colbert whiting with tartar sauce) or cold dishes (black Krim tomato gazpacho with trout roe and mustard; palourde clams from Finistère Sud that arrived fresh earlier that day). As for the sweets, a big bravo for the financier with yellow peaches and peppermint ice cream. There’s a fine selection of wines by the glass, from €5.50 to €8 (Touraine-Amboise from La Grange Tiphaine, Mondeuse from Antoine Petitprez, a Macedonian rosé from Jason Ligas) and bottles from more distant horizons',
    price: 'From 16€ to 35€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Dessirier',
    image: require('../../assets/dessirier.png'),
    subtitle: 'Fish and Shellfish',
    address: '9 place du maréchal juin, 75017 Paris',
    opened: '12:00PM-2:15PM and 7PM-11PM (10PM on sunday)',
    description: 'The restaurant Dessirier is famous for its fishes, seafood and oyster bar. Since 1996, Michel Rostang succeeded to keep up this reputation. The chef, trained at the Rostang school, and its team prepare whole fishes, grilled or “en croûte de sel” from the daily arrival: gorgeous sea bream (1,2 kg), turbot (1,5 kg), sea bass (1,2 kg) or the indispensable sole of 1,2 kg which is unique in Paris but also wonderful creations inspired by all these fresh sea products.'
    + 'With its brand new interior design exalting contemporary Art and Cuisine - the restaurant has been wholly redecorated in August 2010 – Dessirier is the place to be in Paris for a sailing spirit.',
    price: 'Starter + Main Course or Main Course + Dessert: 40€\nStarter + Main Course + Dessert: 48 €',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'La Belle Maison',
    image: require('../../assets/maison.png'),
    subtitle: 'Fish and Shellfish',
    address: '4, rue de Navarin 75009 Paris',
    opened: 'From 12:30pm to 2:30pm and from 7:30pm to 10:30pm\nClosed Sunday and Monday',
    description: 'With his ironclad CV (Constant, Frechon…), Franck Baranger, the gentleman restaurateur from Pantruche and Caillebotte, dove headfirst into this neo-bistro located in the central SoPi neighborhood. Also along for the ride is Andrew Frost (ex-Pétrus in London and Trianon Palace), the brave Welsh captain at the helm of this former Maison Mère, madeover by Emilie Bonaventure. Spread out over two levels in a space with a wood-white-blue-yellow dress code, gourmet diners who split their time between Brooklyn and Deauville share plates of memorable whelks with hay mayo before digging into solo portions of the tasty catch of the day: a volcanic risotto with tender calamari, a celeriac mousseline, fresh hazelnuts, thinly sliced chorizo, purslane, chive oil and a charred onion broth; a stunning, pearly white line-caught whiting, oven-roasted with thyme and olive oil, served with a monumental potato millefeuille with seaweed butter, charred and braised romaine lettuce, Bordelaise sauce, capers and beef bone marrow; and a Philippe Conticini-like finale with a wild tarte tatin, a monolith of soft apples, wood sorrel and double cream. To drink with all that? Beaujolais rouge from Philippe Jambon and Viré-Clessé from Denis Jeandeau',
    price: 'From 35€ to 50€',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'La Marée Jeanne',
    image: require('../../assets/jeanne.png'),
    subtitle: 'Fish and Shellfish',
    address: '3 rue Mandar 75002 Paris',
    opened: 'Everyday, from noon to 2pm and from 7pm to 10:30pm.',
    description: 'The opening of a seafood bistrot in Paris is rare thing that’s worth celebrating! A cool bistrot at that, and one that’s not too expensive, a mix between the experimental Clamato and the classic Montparnasse institutions: a tiled navy blue kitchen counter, a small (Isigny) oyster bar, a contemporary dining room with Prouvé-style chairs and a wine cellar for big groups. You can rest assured that the house is trustworthy, given that it’s run by Frédéric Hubig (Astier, Jeanne A and Jeanne B). So keep the (small or large) plates of cooked fish coming: dog cockle clams en escabèche; lobster consommé with peppercorns and coconut; salmon quenelles; bass tartare with seaweed and an oyster emulsion; a sweet marinated monkfish with a citrus vinaigrette and Kalamata olive purée; fried smelt (with aïoli, ginger, sweet potato chips and spring onions); an excellent whiting fish with sauce gribiche; a good, old-fashioned bouillabaisse; or the famous lobster croque monsieur, the star of the previously mentioned Jeanne A and B. And to help you get your sea legs? Half pints and galopins (12.5cl) of beer on tap (Czech Knout 10 pilsner, English Neck Oil IPA…) and nice wines (Montlouis Bubulle de Jousset, Muscadet Luneau Papin, Soave Filippi, Jurançon de Hours) that are classy enough to hold their own with an aged Bordier comté or a homemade crème aux oeufs custard. One suggestion : avoid the downstairs dining room',
    price: 'From 16€ to 35€',
    price_tag: '€',
    reservation: true,
  },
];
