export default [
  {
    title: 'Rococo',
    image: require('../../assets/rococo.png'),
    subtitle: 'Kebabs',
    address: '4, rue du Faubourg-Saint-Martin',
    opened: 'Everyday, nonstop from noon to midnight',
    description: 'After Roca, his neo-bistro, and Roco, his neo-pizzeria, Alexandre Giesbert (backed up at Rococo by Chloé Charles, from Septime) has opened up a neo-kebab shop where everything is 100% homemade: from the ketchup to the Corinthian mustard, not to mention the marinades and the incredibly soft bread. A “fine kebab,” which he serves in what could be a modern Turkish café with black tables, Breuer wicker chairs, waxed concrete and a chipboard ceiling with hanging light bulbs.',
    price: 'Menus under 15€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Le Camion qui fume',
    image: require('../../assets/camion.png'),
    subtitle: 'Burgers',
    address: '168 Rue Montmartre, 75002 Paris',
    opened: 'Monday-Sunday from 12PM to 11PM',
    description: 'The burgers from California native Kristin Frederick topped all the cult “made in Paris” food lists ever since 2011: the Classique (beef ground in-house, cheddar, lettuce, onions, pickles, tomatoes, mayonnaise), Campagne (sautéed mushrooms with herbs, caramelized onions, étivaz), Bleu (fourme d’Ambert and port sauce), Californie (a chicken patty with herbs and a honey mustard sauce), Végétarien (button mushrooms, cheddar, lettuce, onions, pickles, tomato, mayo)…. You’ll need to arm yourself with patience (expect a lonnnnng wait) if you want a taste, with fries, onion rings or homemade coleslaw',
    price: 'Menus under 15€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'PNY Paris New York',
    image: require('../../assets/pny.png'),
    subtitle: 'Burgers',
    address: '50, rue du Faubourg Saint-Denis 75010 Paris',
    opened: 'From noon to 3pm (4pm Saturday and Sunday)\nFrom 7pm to 11pm (11:30pm Saturday and Sunday)',
    description: 'Plump brioche buns fresh out of the ovens at Rachel’s Cake, dry-aged beef from Ponclet (ground in-house) and mouthwatering toppings, the burgers at PNY have everyone feeling good. We should mention that there’s plenty of choice: avocado, aged cheddar and a secret sauce for the Morning California; cheddar, smoked bacon, onion rings and BBQ sauce for the Return of the Cowboy; breaded chicken breast with cheddar, smoked bacon and the PNY sauce for the Crispy, etc. And the new Héritage burger, with steak and onions dripping in butter…. A few other good things about this place: matchstick fries, interior design by Cut Architectures and Pozzetto ice creams for gourmet junkies',
    price: 'From 16€ to 35€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Big Fernand',
    image: require('../../assets/fernand.png'),
    subtitle: 'Burgers',
    address: '55, rue du Faubourg Poissonnière 75010 Paris',
    opened: 'From noon to 10:30pm (nonstop Saturday until 11pm)',
    description: 'Ever since the opening of the first location on rue du Faubourg-Poissonnière in 2012, the Big Fernands have multiplied: in Paris, but also in Lille, Marseille, Lyon, Bordeaux, Nantes, London and even Hong Kong! With its hunting den-like decor and French touches (the staff wear berets, the burgers are named things like Victor, Philibert, Alphonse and Lucien…), it wouldn’t be worth a glass of Gallia if the sourcing of the products wasn’t so impressive: baker’s bread, French beef, raw milk cheeses, homemade sauces. And even if the burgers aren’t huge, they are top of the line. Take the Bartholomé with really juicy beef, raclette cheese, bacon, onion confit and a mix of cocktail and barbecue sauces; or one that isn’t on the menu but which you can make yourself by selecting the ingredients of your choice: beef, lamb, chicken, veggie (champignon de Paris mushrooms), tomme, fourme, goat cheese, herbs, vegetables…. On the side, the fries are sprinkled with paprika and are better than the desserts',
    price: 'Menus under 15€',
    price_tag: '€',
    reservation: false,
  },
];
