export default [
  {
    title: 'Hero',
    image: require('../../assets/hero.png'),
    subtitle: 'Korean, Asian',
    address: '289, rue Saint-Denis 75002 Paris',
    opened: 'From noon to 2:30 pm and from 7pm to 10:45pm\nClosed Monday.',
    description: 'After Candelaria, Glass and Mary Celeste, this gifted team of mixologists and cooks has struck again, enchanting Mattias Castro’s sensational Korean dishes with their magic potions. In this strange pandemonium (cinderblocks, marble, tables made from strips of wood, frilly details and projections on the walls) designed by Jeanette Dalrot from Sweden (A&D) and the New York agency Safari Sundays, the affair revolves around yangnyeom: crispy fried chicken, covered in a sweet and sour garlic sauce or a spicy gochu jang sauce. Share everything as much as possible so as not to fill up too quickly, since before, during and after, you’ll want to make room for kimchi, served plain or in mac & cheese, the jellyfish and green apple salad, the buns filled with pork ribs, pickled cabbage and homemade mayo, and even this funny dessert: roasted sweet potato, meringue, chocolate and maple syrup…',
    price: '35€ to 50€',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'Frenchie',
    image: require('../../assets/frenchie.png'),
    subtitle: 'French Gastronomie',
    address: '5, rue du Nil 75002 Paris',
    opened: 'From noon to 2pm (Thursday and Friday)\nFrom 6:30pm to 10pm Monday - Friday\nClosed Saturday and Sunday',
    description: 'That evening, even after a trip to the Rungis produce market at 3am, Grégory Marchand was still as fresh as a daisy. He appears very zen behind the bar, in the chiaroscuro of his dining room with bricks, rafters, and waxed zinc tables. The haute couture five-course menu is relatively relaxed as well: albacore tuna in a tomato and berry gazpacho with licorice; seared langoustines, delivered from Le Guilvinec that morning, with eggplant, miso purée and lemon confit; tender turbot with squid ink, a shellfish emulsion, leeks and haricots verts — magical with a Saumur blanc from Antoine Foucault for €13 a glass; exuberant veal sweetbreads, the first cèpes and the last mirabelle plums of the season, with a lemon sabayon and tonka beans; and a round of applause for the finale, a poached peach with verbena, almond mousse and a delicate lavender sorbet. To wash it all down, the wine collection is just as impressive',
    price: '4-course: 45€\n5-course: 74€',
    price_tag: '€€€',
    reservation: true,
  },
  {
    title: 'Ze Kitchen Gallery',
    image: require('../../assets/zeKitchen.png'),
    subtitle: 'Neo Bistro',
    address: '4, rue des Grands Augustins 75006 Paris',
    opened: 'From noon to 2:30pm and from 7pm to 10:15pm\nClosed Saturday and Sunday',
    description: '“Galerie”? Because the dining room with soft lighting and hardwood floors is decorated with contemporary paintings. “Kitchen”? Because of the magic that been happening there ever since 2001, as William Ledeuil paves the way for Asia-influenced French gastronomy, using ingredients from the very best producers: Bertin, Thiébault, Durant and Yamashita for the vegetables, Bachès for the citrus, Cédric Casanova for the oils, Terroirs d’Avenir for heaps of things…. That evening: a nice zucchini flower stuffed with crab and shrimp and topped with an onion-saffron emulsion; a delicious and plump seared langoustine plunged into a subtle herbaceous bouillon with chanterelle mushrooms and coco de Paimpol beans with a jus de viande; and a small tempest of Asian fusion desserts — chilled coconut soup with vanilla and berries, white chocolate-wasabi ice cream, and nectarine confit, blackberries and verbena sorbet.',
    price: 'Lunch\nStarter + Main Course + Dessert: 48 €\nDinner\n6-course meal: 85 €',
    price_tag: '€€€',
    reservation: true,
  },
  {
    title: 'Dersou',
    image: require('../../assets/dersou.png'),
    subtitle: 'Neo Bistro',
    address: '21, rue Saint-Nicolas 75012 Paris',
    opened: 'From noon to 3pm and from 7:30pm to midnight\nClosed Monday',
    description: 'Dreamt up by a bartender with a large shadow (Amaury Guyot, who is involved in both Sherry Butt and the Prescription Cocktail Club) and a Japanese chef who knows no borders (Taku Sekine, who worked for Ducasse in Tokyo, and at Saturne and Clown Bar in Paris), this space is 50 square meters of ultimate brutalism (construction site decor with walls peeled down to the cinder blocks, and everything, from the floors to the benches, the bar and the tables, done in barely planed timber). Leave your preconceptions at the door and prepare to be wowed by freestyling cuisine and chilling drinks for the “cocktail pairings.”',
    price: '35€ to 50€',
    price_tag: '€€',
    reservation: true,
  },
];
