export default [
  {
    title: 'The Louvre : A Medieval Castle',
    image: require('../../assets/castle.png'),
    subtitle: 'Visits for children only! Time for parents!',
    address: '99 rue de Rivoli, 75001 Paris, France',
    opened: 'upon request',
    description: 'Before becoming a museum, the Louvre was a fortress, a medieval castle, with towers, a dungeon, an armory, etc. ... Children will discover this place full of history for centuries ...',
    price: 'Our rates are based on length of visit:\n\nA three hour visit = 80€ per child ( tour with guide)\nA two hour visit = 60€ per child ( tour with guide)\n\nSPECIAL RATES/REDUCTIONS:\n\nA three hour visit for 2 children from the same family = 140€ (museum tour with guide)\nA two hour visit for 2 children from the same family = 100€ (museum tour with guide)\nAdditional reductions can be negiotiated for larger families with numerous children.\n\nIf you would like your child to be accompanied from your hotel to the site of the visit, there is an additional cost of 10€ per child (transport time + price of ticket)\nFor longer visits (half day or full day), please contact us to receive an estimated price.',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'The Pompidou Center',
    image: require('../../assets/pompidou.png'),
    subtitle: 'Visits for children only! Time for parents!',
    address: 'Place Georges Pompidou, 75004 Paris, France',
    opened: 'upon request',
    description: 'The Pompidou Centre no longer needs an introduction. It was commissioned by President Georges Pompidou, and designed in an original style by the architects Renzo Piano and Richard Rogers. The Beaubourg Museum was inaugurated in 1977. The museum houses the most important collection of contemporary and modern paintings and sculptures in Europe. Likewise, special conferences and workshops are available to help the young public to discover and appreciate modern art and contemporary artists. This is part of the museum\'s policy : to promote understanding and appreciation of modern art',
    price: 'Our rates are based on length of visit:\n\nA three hour visit = 80€ per child ( tour with guide)\nA two hour visit = 60€ per child ( tour with guide)\n\nSPECIAL RATES/REDUCTIONS:\n\nA three hour visit for 2 children from the same family = 140€ (museum tour with guide)\nA two hour visit for 2 children from the same family = 100€ (museum tour with guide)\nAdditional reductions can be negiotiated for larger families with numerous children.\n\nIf you would like your child to be accompanied from your hotel to the site of the visit, there is an additional cost of 10€ per child (transport time + price of ticket)\nFor longer visits (half day or full day), please contact us to receive an estimated price.',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'Musée d’Orsay',
    image: require('../../assets/orsay.png'),
    subtitle: 'Visits for children only! Time for parents!',
    address: '1, Rue de la Légion d\'Honneur, 75007 Paris',
    opened: 'upon request',
    description: 'Find out who are the Impressionists, why they are called and what is their painting technique ... The greatest Impressionist paintings in this beautiful museum',
    price: 'Our rates are based on length of visit:\n\nA three hour visit = 80€ per child ( tour with guide)\nA two hour visit = 60€ per child ( tour with guide)\n\nSPECIAL RATES/REDUCTIONS:\n\nA three hour visit for 2 children from the same family = 140€ (museum tour with guide)\nA two hour visit for 2 children from the same family = 100€ (museum tour with guide)\nAdditional reductions can be negiotiated for larger families with numerous children.\n\nIf you would like your child to be accompanied from your hotel to the site of the visit, there is an additional cost of 10€ per child (transport time + price of ticket)\nFor longer visits (half day or full day), please contact us to receive an estimated price.',
    price_tag: '€€',
    reservation: true,
  },
  {
    title: 'Napoleon',
    image: require('../../assets/napoleon.png'),
    subtitle: 'Visits for children only! Time for parents!',
    address: '129 Rue de Grenelle, 75007 Paris',
    opened: 'upon request',
    description: 'A tour from the Military Museum in the Invalides and the Vendôme Column will reveal part of his brilliant but controversial career. (Alternative) The tour organised between the Military Museum in the Invalides and the Vendôme Column, will reveal to the young visitors part of Napoleon\'s brilliant but controversial carreer. After the visit of the War Museum in the Invalides, where the grave of Napoleon is situated, the young visitors will go to the Place Vendôme to admire the renowned column. The emperor will no longer hold secrets for them ...',
    price: 'Our rates are based on length of visit:\n\nA three hour visit = 80€ per child ( tour with guide)\nA two hour visit = 60€ per child ( tour with guide)\n\nSPECIAL RATES/REDUCTIONS:\n\nA three hour visit for 2 children from the same family = 140€ (museum tour with guide)\nA two hour visit for 2 children from the same family = 100€ (museum tour with guide)\nAdditional reductions can be negiotiated for larger families with numerous children.\n\nIf you would like your child to be accompanied from your hotel to the site of the visit, there is an additional cost of 10€ per child (transport time + price of ticket)\nFor longer visits (half day or full day), please contact us to receive an estimated price.',
    price_tag: '€€',
    reservation: false,
  },
];
