export default [
  {
    name: 'Restaurant du Palais Royal',
    image: require('../../assets/museums.png'),
    subtitle: 'French Food',
    address: '110 galerie de Valois 75001 Paris',
    lat: '48.865517',
    long: '2.338776',
    Opened: 'Monday: Closed\nTuesday: Noon - 2:30PM & 7PM - 10:30PM\nWednesday: Noon - 2:30PM & 7PM - 10:30PM\nThursday: Noon - 2:30PM & 7PM - 10:30PM\nFriday: Noon - 2:30PM & 7PM - 10:30PM\nSaturday: Noon - 2:30PM & 7PM - 10:30PM\nSunday: Closed',
    description: 'Gallic gastronomy, a nimble inventiveness, resplendent grandeur and a tangible passion; these are some of the marks of excellence that define this restaurant, along with six Michelin stars.',
    starter: '19€',
    main: '32€',
    dessert: '17€',
    price: '€€'
  },
  {
    name: 'Hello Hello Burger',
    image: require('../../assets/museums.png'),
    subtitle: 'French Food',
    address: '110 galerie de Valois - 75001 Paris',
    lat: '48.865517',
    long: '2.338776',
    Opened: 'Tuesday to Saturday\nLunch from Noon to 2:30PM\nDinner from 7PM to 10:30PM',
    description: 'Gallic gastronomy, a nimble inventiveness, resplendent grandeur and a tangible passion; these are some of the marks of excellence that define this restaurant, along with six Michelin stars.',
    starter: '19€',
    main: '32€',
    dessert: '17€',
    price: '€€€'
  },
  {
    name: 'Restaurant du Palais Royal',
    image: require('../../assets/museums.png'),
    subtitle: 'French Food',
    address: '110 galerie de Valois - 75001 Paris',
    lat: '48.865517',
    long: '',
    Opened: 'Tuesday to Saturday\nLunch from Noon to 2:30PM\nDinner from 7PM to 10:30PM',
    description: 'Gallic gastronomy, a nimble inventiveness, resplendent grandeur and a tangible passion; these are some of the marks of excellence that define this restaurant, along with six Michelin stars.',
    starter: '19€',
    main: '32€',
    dessert: '17€',
    price: '€€'
  },
  {
    name: 'Hello Hello Burger',
    image: require('../../assets/museums.png'),
    subtitle: 'French Food',
    address: '110 galerie de Valois - 75001 Paris',
    lat: '',
    long: '',
    Opened: 'Tuesday to Saturday\nLunch from Noon to 2:30PM\nDinner from 7PM to 10:30PM',
    description: 'Gallic gastronomy, a nimble inventiveness, resplendent grandeur and a tangible passion; these are some of the marks of excellence that define this restaurant, along with six Michelin stars.',
    starter: '19€',
    main: '32€',
    dessert: '17€',
    price: '€€€'
  },
];
