export default [
{
    title: 'Le Lido',
    image: require('../../assets/lido.png'),
    subtitle: 'Dinner Show',
    address: '16 Av. des Champs-Élysées 75008 Paris',
    lat: '48.869426',
    long: '2.308596',
    opened: 'Opened every day: Dinner at 7PM, Shows at 9PM & 11PM',
    description: 'The Dinner Show was invented here. And it is always within these walls, where it was born, that it is done with the most style. When in Paris, be won over by the charm of our French-style shows and savour the treats for which our gastronomy has become internationally famous.'
    + 'Our Head Chef in charge of a team of 35 cooks and pastry chefs, who serve 190,000 covers a year for the greatest pleasure of all our guests! During dinner, a new experience which exists only at the Lido immerses you in the dazzling light of music and dance. A unique opportunity to take a few steps on the Lido’s legendary stage before the curtain is raised and it’s time for the show!',
    price: 'Show starts at 75€ per person\nShow + Dinner starts at 170€ per person',
    price_tag: '€€',
    reservation: true,
  },
{
    title: 'Moulin Rouge',
    image: require('../../assets/moulinRouge.png'),
    subtitle: 'Dinner Show',
    address: '82 Boulevard de Clichy 75018 Paris',
    lat: '48.884130',
    long: '2.332464',
    opened: 'Opened every day: Dinner at 7PM, Shows at 9PM & 11PM',
    description: 'Since its creation in 1889, the Moulin Rouge has endeavoured to develop a performance concept, a distinctive imagery and a singular universe that are today recognised worldwide, ensuring its success both in France and abroad.',
    price: 'Show starts at 87€ per person\nShow + Dinner starts at 190€ per person',
    price_tag: '€€',
    reservation: true,
  },
{
    title: 'Crazy Horse',
    image: require('../../assets/crazy.png'),
    subtitle: 'Dinner Show',
    address: '12 avenue George V 75008 Paris',
    lat: '48.866006',
    long: '2.302110',
    opened: 'Monday: 8:15PM & 10:45PM\nTuesday: 8:15PM & 10:45PM\nWednesday: 8:15PM & 10:45PM\nThursday: 8:15PM & 10:45PM\nFriday: 8:15PM & 10:45PM\nSaturday: 7PM, 9:30PM & 11:45PM\nSunday: 8:15PM & 10:45PM',
    description: 'The Crazy Horse, the most avant-garde of Parisian cabarets offers a show titled ‘Désirs’. Signed by Philippe Decouflé and Ali Mahdavi, the show is performed by the cabaret’s famous dancers with their curvaceous silhouettes spectacularly highlighted by a traditional play of light and shadows that has made this a top Parisian nightspot since 1951: 90 minutes of captivating choreography on the endless theme of feminine seduction',
    price: 'Show & 1/2 bottle of champagne or two drinks: 125€ (unique category)',
    price_tag: '€€',
    reservation: true,
  },
{
    title: 'Bel Canto',
    image: require('../../assets/canto.png'),
    subtitle: 'Dinner Show',
    address: '72 quai de l’Hôtel de Ville 75004 Paris',
    lat: '48.854785',
    long: '2.354478',
    opened: 'Everyday from 7:30PM to Midnight',
    description: 'Come and dine on stage at the Bel Canto Restaurant. Every evening, the Bel Canto restaurants combine Opera and fine dining with an elegant twist. All evening, Rigoletto, Figaro, Violetta and Carmen come to the table at the Bel Canto. The proximity of their voices creates a real sensation of excitement and enchants with a same sunshine the Opera lovers and a less initiated public',
    price: 'Formula Dinner & Show from 85€ per person (including the show and the semi gastronomic dinner with an “à la carte” 3 course menu starters / main course /cheeses or dessert)\n Drinks not included',
    price_tag: '€€',
    reservation: true,
  },
// {
//     title: 'Opéra de Paris',
//     image: require('../../assets/opera.png'),
//     subtitle: 'Opera',
//     address: 'Place de l’Opéra 75009 Paris',
//     opened: 'Every first Sunday of each month at 10am (2.5 hours approx.)',
//     description: 'An integral part of the classical music calendar is the programme at the Opéra de Paris (Tosca de Giacomo Puccini, Eliogabalo de Francesco Cavalli, Samson et Dalila, de Camille Saint-Saëns, Lucia du Lammermoor de Gaetano Donizetti, Iphigénie en Tauride de CW Gluck, Les contes d\'Hoffmann de Jacques Offenbach...), a bastion of French culture with two legendary venues, the Opéra Bastille and the Palais Garnier, and a top-flight opera repertoire. It is a highlight of the cultural scene in Paris and opera lovers can expect some very fine performances.',
//     price: '10€ to 150€',
//     price_tag: '€',
//     reservation: true,
//   },
// {
//     title: 'Oliver Twist Musical',
//     image: require('../../assets/oliver.png'),
//     subtitle: 'musical',
//     address: 'Salle Gaveau, 45-47 Rue La Boétie ​75008 Paris',
//     opened: 'Friday 8:30PM\nSaturday 3PM & 8:30PM\nSunday 2PM & 6:30PM',
//     description: 'A listed historical building, La Salle Gaveau is located just a stone’s throw away from the renowned Champs Élysées. It was built in 1907 and played a unique role in both world wars, providing performances specifically for soldiers and those injured in war. A perfect venue for ‘Oliver Twist the Musical’, it is traditionally charming and has exceptional acoustics which will brighten this jewel of a production.',
//     price: '14€ to 84€',
//     price_tag: '€',
//     reservation: true,
//   },
];

