export default [
{
    title: 'Le Lido',
    image: require('../../assets/lido.png'),
    subtitle: 'Dinner Show',
    address: '16 Av. des Champs-Élysées, 75008 Paris',
    opened: 'Opened every day: Dinner at 7PM, Shows at 9PM & 11PM',
    description: 'The Dinner Show was invented here. And it is always within these walls, where it was born, that it is done with the most style. When in Paris, be won over by the charm of our French-style shows and savour the treats for which our gastronomy has become internationally famous.'
    + 'Our Head Chef in charge of a team of 35 cooks and pastry chefs, who serve 190,000 covers a year for the greatest pleasure of all our guests! During dinner, a new experience which exists only at the Lido immerses you in the dazzling light of music and dance. A unique opportunity to take a few steps on the Lido’s legendary stage before the curtain is raised and it’s time for the show!',
    price: 'Show starts at 75€ per person\nShow + Dinner starts at 170€ per person',
    price_tag: '€€',
    reservation: true,
  },
{
    title: 'Moulin Rouge',
    image: require('../../assets/moulinRouge.png'),
    subtitle: 'Dinner Show',
    address: '82 Boulevard de Clichy, 75018 Paris',
    opened: 'Opened every day: Dinner at 7PM, Shows at 9PM & 11PM',
    description: 'Since its creation in 1889, the Moulin Rouge has endeavoured to develop a performance concept, a distinctive imagery and a singular universe that are today recognised worldwide, ensuring its success both in France and abroad.',
    price: 'Show starts at 87€ per person\nShow + Dinner starts at 190€ per person',
    price_tag: '€€',
    reservation: true,
  },
{
    title: 'Opéra de Paris',
    image: require('../../assets/opera.png'),
    subtitle: 'Opera',
    address: 'Place de l’Opéra 75009 Paris',
    opened: 'Every first Sunday of each month at 10am (2.5 hours approx.)',
    description: 'An integral part of the classical music calendar is the programme at the Opéra de Paris (Tosca de Giacomo Puccini, Eliogabalo de Francesco Cavalli, Samson et Dalila, de Camille Saint-Saëns, Lucia du Lammermoor de Gaetano Donizetti, Iphigénie en Tauride de CW Gluck, Les contes d\'Hoffmann de Jacques Offenbach...), a bastion of French culture with two legendary venues, the Opéra Bastille and the Palais Garnier, and a top-flight opera repertoire. It is a highlight of the cultural scene in Paris and opera lovers can expect some very fine performances.',
    price: '10€ to 150€',
    price_tag: '€',
    reservation: true,
  },
{
    title: 'Oliver Twist Musical',
    image: require('../../assets/oliver.png'),
    subtitle: 'musical',
    address: 'Salle Gaveau, 45-47 Rue La Boétie ​75008 Paris',
    opened: 'Friday 8:30PM\nSaturday 3PM & 8:30PM\nSunday 2PM & 6:30PM',
    description: 'A listed historical building, La Salle Gaveau is located just a stone’s throw away from the renowned Champs Élysées. It was built in 1907 and played a unique role in both world wars, providing performances specifically for soldiers and those injured in war. A perfect venue for ‘Oliver Twist the Musical’, it is traditionally charming and has exceptional acoustics which will brighten this jewel of a production.',
    price: '14€ to 84€',
    price_tag: '€',
    reservation: true,
  },
];
