export default [
  {
    title: 'Fondation Louis Vuitton',
    image: require('../../assets/vuitton.png'),
    subtitle: 'Galeries & Co',
    address: '8 avenue du Mahatma Gandhi - 75016 Paris',
    opened: 'OUTSIDE OF SCHOOL HOLIDAYS:\n\nMonday: Noon - 7PM\nTuesday: Closed\nWednesday: Noon - 7PM\nThursday: Noon - 7PM\nFriday: Noon - 11PM\nSaturday: 11am - 8PM\nSunday: 11am - 8PM\n\nDURING SCHOOL HOLIDAYS (November, Christmas, Winter and Spring):\n\nMonday: 10am - 8PM\nTuesday: 10am - 8PM\nWednesday: 10am - 8PM\nThursday: 10am - 8PM\nFriday: 10am - 11PM\nSaturday: 10am - 8PM\nSunday: 10am - 8PM',
    description: 'The Fondation Louis Vuitton, situated in the Bois de Boulogne, a stone\'s throw from the Jardin d’Acclimatation, opened its doors on 27 October 2014. The Foundation\'s exceptional contemporary art collections (permanent and temporary) are exhibited in an architectural gem designed by the American Frank Gehry. This visionary architect has revolutionised the use of glass and created previously unimagined shapes to produce a unique and innovative light and airy building. In addition to the artistic and architectural richness of the Fondation Louis Vuitton, the visitor is also afforded wonderful panoramic views from the various terraces of the building',
    price: 'Full fare: 14€\n-26 year old, students, teachers: 10€\n-18 years old: 5€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Fondation Cartier',
    image: require('../../assets/cartier.png'),
    subtitle: 'Galeries & Co',
    address: '261 boulevard Raspail - 75014 Paris',
    opened: 'Monday: Closed\nTuesday: 11AM - 10PM\nWednesday: 11AM - 8PM\nThursday: 11AM - 8PM\nFriday: 11AM - 8PM\nSaturday: 11AM - 8PM\nSunday: 11AM - 8PM',
    description: 'The Cartier foundation for contemporary art, which opened in 1994, is located on Boulevard Raspail in the 14th arrondissement of Paris. The stunning glass building designed by architect Jean Nouvel blurs the boundary between interior and exterior space. The foundation hosts major contemporary art exhibitions, both themed and specially commissioned, in a variety of media (photography, painting, video, fashion, live shows) as well as special events known as Soirées Nomades (Nomadic Nights). Round off your visit with a foray into the garden, a work of art in itself, created by artist Lothar Baumgarten',
    price: 'Full fare: 10.50€\nStudents: 7€\n-13 years old & -18 years old on wednesdays: Free',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'La Maison Rouge',
    image: require('../../assets/rouge.png'),
    subtitle: 'Galeries & Co',
    address: '10 boulevard de la Bastille - 75012 Paris',
    opened: 'Monday: 11AM - 7PM\nTuesday: Closed\nWednesday: 11AM - 7PM\nThursday: 11AM - 9PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: 11AM - 7PM\n\nBetween exhibitions, the Maison Rouge is closed to the public',
    description: 'The Maison Rouge is a private foundation aiming to promote contemporary design by organizing temporary exhibitions: giving visitors the opportunity to see major private collections with an international dimension, while also devoting themselves to monographic or specialized exhibitions. The space, spread over 2,000 m², belongs to a former factory built around a house',
    price: 'Full fare: 8€\nStudents, 13-18, >65: 5.5€\n-13 years old & disabled visitors: Free',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Gaîté Lyrique',
    image: require('../../assets/gaite.png'),
    subtitle: 'Galeries & Co',
    address: '3 bis rue Papin - 75003 Paris',
    opened: 'Monday: Closed\nTuesday: 2PM - 8PM\nWednesday: 2PM - 8PM\nThursday: 2PM - 8PM\nFriday: 2PM - 8PM\nSaturday: 2PM - 8PM\nSunday: Noon - 6PM',
    description: 'La Gaîté Lyrique is dedicated to digital culture and holds exhibitions, workshops, concerts, talks and screenings. It is a mix between an art gallery, a concert venue and a place of artistic creation. TV and radio programmes are regularly played on their \'Media Platform\'. La Gaîté Lyrique also has a line-up aimed at young people and three different places to eat',
    price: 'Exhibitions prices ranging from 5€ to 30€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Galerie Perrotin',
    image: require('../../assets/perrotin.png'),
    subtitle: 'Galeries & Co',
    address: '76 rue de Turenne - 75003 Paris',
    opened: 'Monday: Closed\nTuesday: 11AM - 7PM\nWednesday: 11AM - 7PM\nThursday: 11AM - 7PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: Closed',
    description: 'The Emmanuel Perrotin Gallery – one of the most prestigious in the capital – opened its doors in 1989. It’s found inside a town house down the Rue de Turenne in the Marais quarter. Its director, Emmanuel Perrotin, brings to light works by the biggest artists from both France and abroad – Maurizio Cattelan, Takashi Murakami, Wim Delvoye, Paola Pivi, Sophie Calle, Pierre Soulages, JR, Jean-Michel Othoniel, Claude Rutault, Xavier Veilhan… and the emerging stars of the current contemporary art market. Other addresses: 10 impasse Saint Claude - 75003 Paris and Hôtel Le Grand Veneur, 60 rue de Turenne - 75003 Paris',
    price: 'Exhibitions prices ranging from 5€ to 30€',
    price_tag: '€',
    reservation: true,
  },
];

