export default [
  {
    title: 'Paris Museum Pass',
    image: require('../../assets/pass.png'),
    subtitle: 'Multiple Museums',
    address: 'All over Paris',
    opened: 'Please refer to desired museums\' opening times',
    description: 'Unlimited access to more than 50 museums and monuments in Paris and the surrounding area.  Visit as many times as you like, and without having to queue, more than 60 museums and monuments in Paris and the surrounding area! The Paris Museum Pass is available for 2, 4 or 6 consecutive days.\n\nArc de Triomphe\nMusée de l’Armée - Tombeau de Napoléon 1er\nCentre Pompidou - Musée national d’art moderne\nMusée national des Arts asiatiques - Guimet\nMusée des Arts décoratifs\nEspaces Mode et Textile\nEspaces Publicité\nMusée Nissim de Camondo\nMusée des Arts et Métiers\nMusée du quai Branly - Jacques Chirac\nChapelle expiatoire\nLa Cinémathèque française - Musée du Cinéma\nCité des Sciences et de l’Industrie - universcience\nConciergerie\nMusée national Eugène Delacroix\nVisite publique des Égouts de Paris\nPalais de la Porte Dorée - Musée national de l\'histoire de l\'Immigration\nMusée de l’Institut du Monde arabe\nMusée d\'art et d\'histoire du Judaïsme\nMusée du Louvre\nMusée national de la Marine\nCité de l’Architecture et du Patrimoine - Musée des Monuments français\nMusée Gustave Moreau\nMusée de Cluny - Musée national du Moyen Âge\nPhilharmonie de Paris - Musée de la musique\nCrypte archéologique du Parvis Notre-Dame\nTours de Notre-Dame\nMusée national de l’Orangerie\nMusée de l’Ordre de la Libération\nMusée d’Orsay\nPalais de la découverte - universcience\nPanthéon\nMusée national Picasso-Paris\nMusée des Plans-reliefs\nMusée Rodin\nSainte-Chapelle\nEN RÉGION PARISIENNE\nMusée de l’Air et de l’Espace\nMusée d’Archéologie nationale et  Domaine national de Saint-Germain-en-Laye\nSèvres, Cité de la céramique - Musée national de la céramique\nAbbaye royale de Chaalis\nChâteau de Champs-sur-Marne\nMusées et domaine nationaux du Palais de Compiègne\nMusée Condé - Château de Chantilly\nMusée départemental Maurice Denis\nChâteau de Fontainebleau\nChâteau de Maisons\nMusée national du château de Malmaison\nChâteau de Pierrefonds\nMusée national de Port-Royal des Champs\nChâteau de Rambouillet, Laiterie de la Reine et Chaumière aux Coquillages\nMusée national de la Renaissance - Château d’Ecouen\nMaison d’Auguste Rodin à Meudon\nBasilique cathédrale de Saint-Denis\nVilla Savoye\nChâteaux de Versailles et de Trianon\nChâteau de Vincennes\n',
    price: 'Free for under 18s and 18-25s EU members. For all the others:\nParis Museum Pass 2 days: 48€\nParis Museum Pass 4 days: 62€\nParis Museum Pass 6 days: 74€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Le Louvre',
    image: require('../../assets/museums.png'),
    subtitle: 'Most Famous',
    address: '99 rue de Rivoli, 75001 Paris',
    opened: 'Monday: 9AM - 6PM\nTuesday: Closed\nWednesday: 9AM - 9:45PM\nThursday: 9AM - 6PM\nFriday: 9AM - 9:45PM\nSaturday: 9AM - 6PM\nSunday: 9AM - 6PM\n\nClosed on the following holidays: January 1, May 1, December 25',
    description: 'Louvre, the world’s largest and most-visited museum, drawing nearly 10 million people each year. It is a museum dedicated to education, with the primary mission to preserve and pass on our heritage to future generations. Originally a simple defensive fortress, the Louvre was for a long time one of the main residences of French kings. It became a museum in 1793, and now exhibits over 73,000 sq. m of Western artworks from the Middle Ages to 1848, as well as the art of the ancient civilizations that preceded and influenced them. Some 35,000 artworks are on display, the oldest of which date back over seven thousand years. The museum collections are grouped into eight curatorial departments: Egyptian Antiquities; Greek, Etruscan, and Roman Antiquities; Near Eastern Antiquities; Islamic Art; Paintings; Sculptures; Decorative Arts; and Prints and Drawings',
    price: 'Free for under 18s and 18-25s EU members. For all the others: 15€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Musée d’Orsay',
    image: require('../../assets/orsay.png'),
    subtitle: 'Must see',
    address: '1 rue de la Légion d\'Honneur, 75007 Paris',
    opened: 'Monday: Closed\nTuesday: 9:30AM - 6PM\nWednesday: 9:30AM - 6PM\nThursday: 9:30AM - 9:30PM\nFriday: 9:30AM - 6PM\nSaturday: 9:30AM - 6PM\nSunday: 9:30AM - 6PM',
    description: 'Presented in a former train station, the collections of the musée d\'Orsay are among the most famous in the world. The museum presents the artistic production of the period 1848-1914, a decisive period in the art history which gave birth to the masterpieces of Impressionism. You will thus admire great artists such as: Manet, Monet, Van Gogh, Degas, Cézanne, Garnier, Courbet, Carpeaux, Nadar or Guimard',
    price: 'Free for under 18s and 18-25s EU members. For all the others: 12€ (No line: 15€)',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Centre Pompidou',
    image: require('../../assets/pompidou.png'),
    subtitle: 'Must see',
    address: 'Place Georges Pompidou - 75004 Paris',
    opened: 'Monday: 11AM - 9PM\nTuesday: 11AM - 9PM\nWednesday: 11AM - 9PM\nThursday: 11AM - 11PM\nFriday: 11AM - 9PM\nSaturday: 11AM - 9PM\nSunday: 11AM - 9PM',
    description: 'The Centre Pompidou, designed by Renzo Piano and Richard Rogers, is a 20th-century architectural marvel, immediately recognizable by its exterior escalators and enormous coloured tubing. It is home to the National Museum of Modern Art and is internationally renowned for its 20th and 21st century art collections. The works of iconic artists are displayed chronologically over two sections: the modern period, from 1905 to 1960 (Matisse, Picasso, Dubuffet, etc.), and the contemporary period, from 1960 to the present day (Andy Warhol, Niki de Saint Phalle, Anish Kapoor, etc.). In addition to its permanent collections, internationallyrenowned exhibitions are organized every year on the top floor, where visitors can enjoy a breathtaking view of Paris and its rooftops. Everything you might need to spend a pleasant half-day, or indeed a day in the museum is available: eat at Le Georges, learn more at the public information library, and take a break browsing the shelves of the museum gift shop. At the foot of the Centre, the Atelier Brancusi presents a unique collection of works by this artist who played a major role in the history of modern sculpture. Panoramic view over Paris from 6th floor (included in entrance ticket)',
    price: 'Unique Price: 14€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Palais de Tokyo',
    image: require('../../assets/tokyo.png'),
    subtitle: 'Must see',
    address: 'Place Georges Pompidou - 75004 Paris',
    opened: 'Monday: 11AM - 9PM\nTuesday: 11AM - 9PM\nWednesday: 11AM - 9PM\nThursday: 11AM - 11PM\nFriday: 11AM - 9PM\nSaturday: 11AM - 9PM\nSunday: 11AM - 9PM',
    description: 'The Palais de Tokyo occupies a monumental building which was built in 1937 for the Paris International Exhibition dedicated to Art and Technology in Modern Life. It is situated in the 16th arrondissement, a stone\'s throw from Trocadéro and the Eiffel Tower. The west wing of the palace houses one of the largest centres for creation and contemporary art in Europe. Entirely renovated in April 2012 by the architects Anne Lacaton and Jean-Philippe Vasall, the site offers visitors exhibitions, meetings, screenings, concerts and performances in a 22,000 m² space spread across 4 floors. The Little Palais offers special activities and workshops for children. Numerous amenities: two restaurants, including the Tokyo Eat, two gardens and a bookshop. The east wing of the Palais de Tokyo houses the Musée d\'Art Moderne de la Ville de Paris.',
    price: 'Unique Price: 12€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Le Grand Palais',
    image: require('../../assets/grandPalais.png'),
    subtitle: 'Must see',
    address: 'Avenue Winston Churchill - 75008 Paris',
    opened: 'Monday: 10AM - 8PM\nTuesday: Closed\nWednesday: 10AM - 10PM\nThursday: 10AM - 8PM\nFriday: 10AM - 8PM\nSaturday: 10AM - 8PM\nSunday: 10AM - 8PM',
    description: 'The Grand Palais is one of the most iconic Parisian monuments. Built for the 1900 Exposition Universelle, it is recognizable by its large glass dome flanked by the French flag. This architectural masterpiece of stone, steel and glass has been listed as a historical monument since 2000. It comprises 3 major sites: the Nave, the National Galleries and the Palais de la Découverte. The majestic nave, 240 m long, welcomes a wide variety of major national and international events: (horse riding, contemporary art, fairground, etc.). The national galleries organize large-scale exhibitions on artists that have marked the history of art (Picasso, Hopper, Renoir, etc.). The Palais de la Découverte is a museum and cultural centre dedicated to science, where children can learn whilst having fun, through permanent collections and temporary exhibtions. A 3-in-1 site that\'s not to be missed, close to the Champs-Elysées.',
    price: 'Full Price: 14€\n16 to 25 years old: 10€',
    price_tag: '€',
    reservation: true,
  },
];
