export default [
  {
    title: 'Musée des Arts Forains',
    image: require('../../assets/forrain.png'),
    subtitle: 'Small yet awesome',
    address: '53 avenue des Terroirs de France 75012 Paris',
    lat: '48.832605',
    long: '2.389228',
    opened: 'The Pavillons de Bercy organise tours for individuals and groups upon reservation. These tours are guided with fairground rides, games and a show automata.\nTours from Monday to Sunday',
    description: 'The Pavillons de Bercy house 4 different areas:\nThe Musée des Arts Forains\nThe Théâtre du Merveilleux\nThe Salons Vénitiens\nThe Théâtre de Verdure\n\nFull of history, these places receive more than 200,000 visitors each year, either through functions or individual and group visits. Each area has a particular theme: 19th-century fairgrounds at the Musée des Arts Forains, carnival in the Salons Vénitiens, cabinets of curiosity in the Théâtre du Merveilleux and amazing gardens in the Théâtre de Verdure. The biggest collection in Europe of fairground and show objects are displayed here by Jean Paul Favand, the founder of the museums. The decor mixes tradition with modernity and the short-lived with the long lasting to bring the items to life. The unique place, a veritable laboratory of ideas, uses the latest technology in sound and video projection to reveal the soul of heritage objects, to get your imagination going and welcome you into this world of daydreams',
    price: 'Full fare: 16€\n4 to 11 years old: 8€\nUnder 4: FREE',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Musée Maxim\'s',
    image: require('../../assets/maxims.png'),
    subtitle: 'Small yet awesome',
    address: '3 rue Royale 75008 Paris',
    lat: '48.867492',
    long: '2.322246',
    opened: 'Guided tour (Wednesday to Sunday): guided visit in English at 2pm and in French at 3.15pm',
    description: 'Created out of dressmaker Pierre Cardin\'s passions for the Belle Époque and Art Nouveau, this museum is located above the Maxim\'s restaurant, which is a symbol of the 1900s. On three floors, it reconstructs the apartment of a courtesan who experienced the jet-set lifestyle of the time, with masterpieces by Tiffany, Majorelle and Massier. An immersion into the glamorous Paris ... cheeky',
    price: '€20 per person\nReduced price: €10 (jobseekers, French benefit recipients, disabled visitors and their travel companion)\nFree for young people and children under 18',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Musée national Gustave Moreau',
    image: require('../../assets/moreau.png'),
    subtitle: 'Small yet awesome',
    address: '14 rue de la Rochefoucauld 75009 Paris',
    lat: '48.877959',
    long: '2.334413',
    opened: 'Monday: 10AM - 12:45PM & 2PM - 5:15PM\nTuesday: Closed\nWednesday: 10AM - 12:45PM & 2PM - 5:15PM\nThursday: 10AM - 12:45PM & 2PM - 5:15PM\nFriday: 10AM - 5:15PM\nSaturday: 10AM - 5:15PM\nSunday: 10AM - 5:15PM',
    description: 'This house/artist’s studio in the 9th arrondissement houses the collections of painter Gustave Moreau and respects the original museum layout designed by the artist. Over the course of a visit, you will discover no less than 1,300 paintings, watercolours and sketches, and 5,000 drawings. The ground floor, recently renovated, also houses largeformat work. Take your time strolling through the more intimate 1st floor, containing the rooms of the artist’s apartment. Numerous family trinkets and Louis XVI furniture items can be admired. The studios on the 2nd and 3rd floor, separated by a superb spiral staircase, display the artist’s major works',
    price: 'Free for under 18s, under 26s EU members and first sunday of each month\nFor all the others: 6€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Appartement - atelier de Le Corbusier',
    image: require('../../assets/corbusier.png'),
    subtitle: 'Small yet awesome',
    address: '24 rue Nungesser et Coli 75016 Paris',
    lat: '48.843353',
    long: '2.251540',
    opened: 'Saturday: 10AM- 1PM & 1:30PM - 5PM\n\nSpecial tours from Monday to Friday, at an additional fee upon reservation and subject to availability',
    description: 'The Appartement-atelier de Le Corbusier, situated on the top two floors of the Molitor building, was designed and built between 1931 and 1934 by Le Corbusier and Pierre Jeanneret. Le Corbusier lived there until his death and set up his painting workshop there, an activity which he exercised every day of his life',
    price: 'Full fare: 8€\nStudents: 5€ (Student ID required)\nFree for children under 14 and disabled visitors with their travel companion',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Palais Galliera - Musée de la Mode',
    image: require('../../assets/galliera.png'),
    subtitle: 'Small yet awesome',
    address: '10 avenue Pierre Ier de Serbie 75116 Paris',
    lat: '48.865475',
    long: '2.296658',
    opened: 'Monday: Closed\nTuesday: 10AM- 6PM\nWednesday: 10AM- 6PM\nThursday: 10AM- 9PM\nFriday: 10AM- 6PM\nSaturday: 10AM- 6PM\nSunday: 10AM- 6PM',
    description: 'Built in the 19th century, the Palais Galliera now houses the Musée de la Mode de la Ville de Paris. The collections, including some 100,000 pieces of clothing and accessories, are among the richest in the world and reflect the fashion trends and habits of France from the 18th century until modern day. The Musée Galliera follows exclusive temporary exhibitions held two or three times a year. The site has a library and resource centre that is accessible by appointment only',
    price: 'Full fare: 10€\nStudents: 7€',
    price_tag: '€',
    reservation: true,
  },
  {
    title: 'Musée de la vie romantique',
    image: require('../../assets/romantique.png'),
    subtitle: 'Small yet awesome',
    address: '16 rue Chaptal 75009 Paris',
    lat: '48.881099',
    long: '2.333448',
    opened: 'Monday: Closed\nTuesday: 10AM- 6PM\nWednesday: 10AM- 6PM\nThursday: 10AM- 6PM\nFriday: 10AM- 6PM\nSaturday: 10AM- 6PM\nSunday: 10AM- 6PM',
    description: 'The Musée de la Vie Romantique is located in the house of the painter Ary Scheffer, built in 1830. Situated in Pigalle, in La Nouvelle Athènes, the museum recreates a harmonious historical setting evoking the romantic period. The ground floor is devoted to George Sand: portraits, furniture, and jewellery from the 18th and 19th centuries. On the first floor, Ary Scheffer\'s paintings are surrounded by contemporary works. Two annual temporary exhibitions are organized as well as concerts, readings and activities for children. In the museum\'s garden, the seasonal tearoom, a real haven of peace open from March to October, is a great place for a tasty snack',
    price: 'FREE',
    price_tag: 'FREE',
    reservation: true,
  },
];
