export default [
  {
    title: 'Le Silencio',
    image: require('../../assets/silencio.png'),
    subtitle: 'Night Clubs',
    address: '142 rue Montmartre, 75002 Paris',
    opened: 'Monday: Closed\nTuesday: 12AM - 5AM\nWednesday: 12AM - 5AM\nThursday: 12AM - 5AM\nFriday: 12AM - 5AM\nSaturday: 12AM - 5AM\nSunday: Closed',
    description: 'Masterminded and designed by famed filmmaker David Lynch, Club Silencio – named for the theater featured in Mulholland Drive – is a stunning and ultra-exclusive nightclub/bar/concert venue/whatever-eccentric-show-Lynch-has-in-mind-tonight kind of place',
    price: 'Drinks 10€ - 15€ Bottles 120€ - 350€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Le Manko',
    image: require('../../assets/manko.png'),
    subtitle: 'Night Clubs',
    address: '15 Avenue Montaigne, 75008 Paris',
    opened: 'Monday: 12AM - 3PM & 7PM - 2AM\nTuesday: 12AM - 3PM & 7PM - 2AM\nWednesday: 12AM - 3PM & 7PM - 2AM\nThursday: 12AM - 3PM & 8PM - 2AM\nFriday: 12AM - 3PM & 8PM - 2AM\nSaturday: 12AM - 3PM & 8PM - 2AM\nSunday: Closed',
    description: 'With a collection of global restaurants, a compilation of cookbooks to his name and his own TV show in his home country of Peru, chef Gaston Acurio can singlehandedly be credit for bringing Peruvian cuisine to the world’s attention. Afterwards, it\'s just a short climb up the golden Art Deco staircase to visit the Manko Cabaret',
    price: 'Drinks 10€ - 15€ Bottles 120€ - 350€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Le Matignon',
    image: require('../../assets/matignon.png'),
    subtitle: 'Night Clubs',
    address: '3 Avenue Matignon, 75008 Paris',
    opened: 'Monday: 8PM - 2AM\nTuesday: 8PM - 2AM\nWednesday: 8PM - 2AM\nThursday: 8PM - 2AM\nFriday: 8PM - 2AM\nSaturday: 8PM - 2AM\nSunday: 8PM - 2AM',
    description: 'Le Matignon is a must-go for a feverish Parisian night in an international jet- setting atmosphere. Jacques Garcia designed the opulent interior and the ‘restaurant and playground’ (as it markets itself) is owned by two Parisian superpowers, Cyril Péret and again Gilbert Costes. For more fun, go to the Club Matignon: the nocturnal playground located below the restaurant. At Matignon, Garcia has created a luxurious mix of eclectic and opulent, subdued and bold, elegant and funky',
    price: 'Drinks 10€ - 15€ Bottles 120€ - 350€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'YoYo',
    image: require('../../assets/yoyo.png'),
    subtitle: 'Night Clubs',
    address: '13 avenue du Président Wilson 75016 Paris',
    opened: 'Monday: Closed\nTuesday: Closed\nWednesday: Closed\nThursday: Closed\nFriday: 11PM - 5AM\nSaturday: 11PM - 5AM\nSunday: Closed',
    description: 'YoYo is hidden under the Palais de Tokyo, an important contemporary art museum in the westside of Paris. Located in an old "art déco" cinema in the basement of the museum, this space is used for many events like fashion shows or son on but also welcomes live music and clubbing nights several times a month with high level artists',
    price: 'Drinks 10€ - 15€ Bottles 120€ - 350€',
    price_tag: '€€',
    reservation: false,
  },
];
