export default [
  {
    title: 'Gravity Bar',
    image: require('../../assets/gravity.png'),
    subtitle: 'Cocktails & Dinner',
    address: '44, rue des Vinaigriers, 75010 Paris',
    opened: 'Closed Sunday & Monday',
    description: 'The curving wooden interiors of this spot take their inspiration from surfing and skateboarding. The cocktails and the market-driven menu are deliciously sophisticated. Unusual flavours are the draw here; try the Black Popeye, shaken with Chairman\'s Reserve rum, amaro, bitters and absinthe.',
    price: 'Average price for a cocktail: 12€\nAverage price for dinner: 10-19€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Clown Bar',
    image: require('../../assets/clown.png'),
    subtitle: 'Cocktails & Dinner',
    address: '114 rue Amelot, 75011 Paris',
    opened: 'Closed Monday & Tuesday\nOpen Wednesday-Sunday for lunch & dinner',
    description: 'This listed 1902 clown-themed wonder, with its ornate glass ceiling, painted wall tiles and original zinc bar, transports you to a different era. The cocktails are as surprising as the menu that has been deliciously revived by Sota Atsumi’s intriguing product focused small plates.',
    price: 'Average price for a cocktail: 12€\nAverage price for dinner: 40-60€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Bar Ballroom du Beef Club',
    image: require('../../assets/ballroom.png'),
    subtitle: 'Cocktails',
    address: '58, rue Jean-Jacques Rousseau, 75001 Paris',
    opened: 'Closed Sunday\nOpen Wednesday-Saturday from 7:00PM to 2:00AM',
    description: 'You\'ll find red brick walls, an ornate tiled ceiling and a gleaming collection of spirits and liqueurs, which all create the perfect setting for this dimly-lit speakeasy-style cocktail bar. Waistcoat-wearing bartenders serve up drinks and banter at the comptoir, or there are Chesterfield sofas at candlelit tables for more intimacy.',
    price: 'Average price for a cocktail: 13-15€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Experimental Cocktail Club',
    image: require('../../assets/experimental.png'),
    subtitle: 'Cocktails',
    address: '37 rue Saint-Sauveur , 75002 Paris',
    opened: 'Monday-Thursday: 7:00PM to 2:00AM\nFriday-Saturday: 7:00PM to 4:00AM\nSunday: 8:00PM to 2:00AM',
    description: 'After the Experimental Cocktail Club’s mixes, you’ll never go back to the boring drinks that are to cocktail bars. There are DJ sets at weekends where you can dance the night away. Or stop by in the week when you can really enjoy the venue as at the weekend, it is difficult to find a seat!',
    price: 'Average price for a cocktail: 13-15€',
    price_tag: '€€',
    reservation: false,
  },
];
