export default [
  {
    title: 'Demory Paris',
    image: require('../../assets/demory.png'),
    subtitle: 'Craft beers',
    address: '62 rue Quincampoix, 75004 Paris',
    opened: 'Monday: 6PM - 2AM\nTuesday: 6PM - 2AM\nWednesday: 6PM - 2AM\nThursday: 6PM - 2AM\nFriday: 6PM - 4AM\nSaturday: 6PM - 4AM\nSunday: Closed',
    description: 'Now in its more or less permanent form (see From Demory Paris and Les Dessous de Paris), Demory’s flagship bar remains a convivial spot to enjoy Demory’s brews or one of the six guest beers from international craft breweries. Handmade chicken, pork or veal sausages from their own kitchen provide sustenance for a night of dancing to top DJs or simply a pre-movie or post-museum snack (the nearby MK2 shows arthouse films and the Centre Pompidou is just a block away)',
    price: 'Pints from 5 to 12€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'La Fine Mousse',
    image: require('../../assets/mousse.png'),
    subtitle: 'Craft beers',
    address: '6 avenue Jean Aicard, 75011 Paris',
    opened: 'Monday: 5PM - 2AM\nTuesday: 5PM - 2AM\nWednesday: 5PM - 2AM\nThursday: 5PM - 2AM\nFriday: 5PM - 2AM\nSaturday: 5PM - 2AM\nSunday: 5PM - 2AM',
    description: 'Boasting the very best selection of craft beers on tap in Paris, as well as a bottle collection that brings the total offer up to 150 different beers, La Fine Mousse is certainly one of the city’s most well-stocked beer bars. It’s also one of the most expensive. French craft beers share real estate with lesser-known Belgians and German brews, with room left over for the USA, the Netherlands, and less-represented places like Norway and Italy to show off their brewing prowess',
    price: 'Pints from 5 to 12€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Frog XVI',
    image: require('../../assets/frog.png'),
    subtitle: 'Craft beers',
    address: '110 bis Avenue Kléber, 75016 Paris',
    opened: 'Monday: 11:30AM to 1AM\nTuesday: 11:30AM to 1AM\nWednesday: 11:30AM to 2AM\nThursday: 11:30AM to 2AM\nFriday: 11:30AM to 2AM\nSaturday: 11AM to 2AM\nSunday: 11AM to 1AM',
    description: 'FROG XVI is stylishly decorated whilst conserving the warmth and conviviality of an English pub that can boast a magnificent microbrewery and a bar/restaurant on two levels',
    price: 'Pints from 5 to 12€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Dirty Dick',
    image: require('../../assets/dick.png'),
    subtitle: 'Craft beers',
    address: '10 rue Crochet, 75009 Paris',
    opened: 'Monday: 6PM - 2AM\nTuesday: 6PM - 2AM\nWednesday: 6PM - 2AM\nThursday: 6PM - 2AM\nFriday: 6PM - 2AM\nSaturday: 6PM - 2AM\nSunday: 6PM - 2AM',
    description: 'Don’t let the name deter you. You might be in Pigalle, but you won’t need to get tested after visiting this refreshingly original tiki-style lounge bar with a smorgasbord of beverages to please all tastes. Boozehounds can get giggly-tipsy off tropical cocktails or entertain dangerously high BAC levels over shared flaming scorpion bowls. Liquor aside, it’s the small but select beer stock that should not be overlooked, especially when pints start at 5 euros a pop — a rare find outside of Parisian happy hours. Here you can get Newcastle on tap, in addition to a few other uncommon craft beers and imported bottles for those who are tired of getting buzzed off Leffe and Heineken',
    price: 'Pints from 5 to 12€',
    price_tag: '€',
    reservation: false,
  },
];
