export default [
  {
    title: 'Frenchie bar à vin',
    image: require('../../assets/frenchieWine.png'),
    subtitle: 'Wine bar',
    address: '6, rue du Nil, 75002 Paris',
    opened: '7/7 without reservations. The kitchen is open from 7PM to 11PM',
    description: 'A spontaneous eatery, one for every budget, with no reservations required and more choices. Thus he created the cave à manger, where people come to eat smaller portions of the restaurant’s dishes, to share and to savour, and can also discover UK-made cheeses and a wide selection of wines by the glass',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Chez Nous',
    image: require('../../assets/chezNous.png'),
    subtitle: 'Organic Wines',
    address: '10, rue Dauphine, 75006 Paris',
    opened: 'Everyday from 6PM to 12AM',
    description: 'In 2014, a pair of friends launched this little Left Bank bar, which features organic products by small producers. It’s not a big-name affair, but you should expect a smattering of tourists among the smiling locals gathered here. A warm welcome, good food, and good wine are all that it takes -- and it’s located right near the Pont Neuf, so you won’t have to go hunting',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'La Buvette',
    image: require('../../assets/buvette.png'),
    subtitle: 'Wine bar',
    address: '67 Rue Saint-Maur, 75011 Paris',
    opened: 'Monday - Friday 8:30AM - 12AM\nSaturday - Sunday 10AM - 12AM',
    description: 'Everything in this enchanting tiny bar is minimalist but perfect, from the small 50-odd list of surprising wines to the half-a-dozen delicate sharing plates, handwritten on a mirror, often including broad beans and lemon zest, fresh goat’s cheese with black garlic and cherries, and marinated baby octopus with saffron...',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Vingt heures vin',
    image: require('../../assets/vingt.png'),
    subtitle: 'Wine bar',
    address: '17 Rue Joseph de Maistre, 75018 Paris',
    opened: 'Tuesday - Sunday 7PM - 1AM',
    description: 'The 18th arrondissement is becoming a scene of sorts, and Vingt Heures Vin the go-to for wine bars in the neighborhood. It offers over 170 wines, and most come directly from their producers. It has all the trappings of a solid wine bar, with honey-roasted camembert, Spanish ham, and foie gras. Tiny, quaint, sometimes rowdy, but always a good bet, it’s just far enough away from the touristy parts of Montmartre to still be appropriately cool',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Le Dauphin',
    image: require('../../assets/dauphin.png'),
    subtitle: 'Wine bar',
    address: '131 Avenue Parmentier, 75011 Paris',
    opened: 'Tuesday - Saturday 6PM - 2AM (last order at 11:30PM)',
    description: 'For those who can’t get into the adjacent restaurant Le Chateaubriand, you can taste the wares at their wine bar next door. Le Dauphin isn’t the most charming place to share a few glasses of wine its glass façade looks onto bustling rue Parmentier but the creative small plates and natural wines still make it a mainstay',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'Les Caves Legrand',
    image: require('../../assets/legrand.png'),
    subtitle: 'Wine bar',
    address: '1 Rue de la Banque, 75002 Paris',
    opened: 'Monday 11AM - 7PM\nTuesday - Friday 10AM - 7:30PM\nSaturday 10AM - 7PM',
    description: 'For a delightfully old-timey feel, this wine bar, located in the 19th century covered passage Galerie Vivienne, brings the charm. It is unabashedly French when it comes to wine, so don’t expect more exotic quaffs. It’s not really a scene as far as entertainment is concerned, but for a calmer glass and some nibbles, you can’t really beat it. Great for when grandma’s in town',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
  {
    title: 'La Compagnie des vins surnaturel',
    image: require('../../assets/surnaturel.png'),
    subtitle: 'Wine bar',
    address: '7 Rue Lobineau, 75006 Paris',
    opened: 'Everyday from 6PM to 2AM',
    description: 'For something a little daintier, this cozy spot features plush chairs and couches instead of the typical wooden tables you might see in most wine bars. Burrata and prosciutto pair nicely with the hundreds of wines available, and the staff is always ready to share advice. It’s not a party scene, or particularly trendy, but it’s a solid place to enjoy something a bit more intimate and refined',
    price: 'Average price for a glass: 6€',
    price_tag: '€',
    reservation: false,
  },
];
