export default [
  {
    title: 'Colette',
    image: require('../../assets/colette.png'),
    subtitle: 'Concept store - Luxury & Women & Men & Lifestyle',
    address: '213 rue Saint-Honoré, 75001 Paris',
    opened: 'Monday: 11AM - 7PM\nTuesday: 11AM - 7PM\nWednesday: 11AM - 7PM\nThursday: 11AM - 7PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: Closed',
    description: 'Without doubt the best-known concept store in Paris, Colette has great prestige within the fashion world as it stocks a wide selection of some of world’s most elite fashion brands, including Céline, Givenchy and Raf Simons. Other highlights of the store include a ground-floor art gallery and a water bar which offers over 150 brands of water',
    price: '€€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'L\'Eclaireur',
    image: require('../../assets/eclaireur.png'),
    subtitle: 'Concept store - Women & Men',
    address: '40, Rue de Sévigné, 75003 Paris',
    opened: 'Monday: 11AM - 7PM\nTuesday: 11AM - 7PM\nWednesday: 11AM - 7PM\nThursday: 11AM - 7PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: Closed',
    description: 'Since 1980, when our first space opened in an art gallery on the Champs-Elysées, LECLAIREUR has been presenting designers with strong, unusual and rich approaches to their work. LECLAIREUR was quickly established as a visionary force in the world of fashion, lifestyle and design. LECLAIREUR is forever a pioneer, regularly reinventing itself to offer its clientele a unique vision of creation, just as it did, some 35 years ago',
    price: '€€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'The Broken Arm',
    image: require('../../assets/brokenArm.png'),
    subtitle: 'Concept Store - Women & Men & Lifestyle',
    address: '12 Rue Perrée, 75003 Paris',
    opened: 'Monday: Closed\nTuesday: 11AM - 7PM\nWednesday: 11AM - 7PM\nThursday: 11AM - 7PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: Closed',
    description: 'The Broken Arm is the latest Parisian concept shop to offer fashion, accessories, and lifestyle items alongside a charming café. What sets this third-arrondissement boutique apart from the competition, however, is its highly personal vibe. The adjacent café — which some say serves the best coffee in Paris — offers a similarly singular vibe. No wonder the airy, plant-filled spot has become a hangout for fashion insiders and creative types alike',
    price: '€€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Tom Greyhound',
    image: require('../../assets/greyhound.png'),
    subtitle: 'Concept store - Women & Men',
    address: '19 Rue de Saintonge, 75003 Paris',
    opened: 'Monday: 11AM - 7PM\nTuesday: 11AM - 7PM\nWednesday: 11AM - 7PM\nThursday: 11AM - 7PM\nFriday: 11AM - 7PM\nSaturday: 11AM - 7PM\nSunday: Closed',
    description: 'Tom Greyhound Paris is the first international outpost of eponym Seoul-based concept store. The fashion industry\'s most famous names, such as Alexander Wang, 3.1.Phillip Lim, Jil Sander share the spotlight with up-and-coming talent. Designers such as J.W. Anderson, Roksanda Ilincic or Etienne Deroeux therefore bring new and fresh perspectives to a discerning clientele',
    price: '€€',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Les Suites',
    image: require('../../assets/suites.png'),
    subtitle: 'Concept Store - Luxury',
    address: '47 rue Pierre Charron, 75008 Paris',
    opened: 'Upon appointment',
    description: 'Les Suites offer three super private dressing rooms decorated to evoke classical periods in French history. They\'re the perfect settings to try on any of the one-of-a-kind couture pieces by Giambattista Valli, Elie Saab, Ulyana Sergeenko, or Manish Arora that the boutique carries. For the ultimate in luxury, there\'s also a team of personal stylists and on-site tailors on hand to make sure everything fits exactly as it should.',
    price: '€€',
    price_tag: '€€',
    reservation: true,
  },
];
