export default [
  {
    title: 'L\'Eclaireur Homme',
    image: require('../../assets/homme.png'),
    subtitle: 'Men only',
    address: '26 avenue des Champs Elysées 75008 Paris',
    opened: 'Monday - Saturday 11AM - 7PM',
    description: 'L’eclaireur is a small empire of cutting-edge multi-brands, and this particular storefront is dedicated to menswear, promoting both emerging and established labels including Comme des Garçons, Martin Margiela, Carpe Diem, and Junya Watanabe. With its raw, industrial décor, the boutique is not unlike a modern arts gallery: garments are put under spotlights and accessories are arranged in glass cabinets des curieux.',
    price: 'mid-high',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'mid-high',
    image: require('../../assets/balibaris.png'),
    subtitle: 'Men only',
    address: '21, rue St Sulpice, 75006',
    opened: 'Monday 11AM - 7:30PM\nTuesday - Friday 10:30AM - 7:30PM\nSaturday 10:30AM - 8PM',
    description: 'On Rue de Marseille on the Canal St Martin, Balibaris is in good company, alongside other quality French outfitters such as A.P.C. and Agnès b. This label produces an elegant wardrobe for the contemporary man, made with quality materials in specialised workshops throughout Europe. Don’t miss the extensive tie collection, featuring everything from limited edition alpaca-knit neckties to traditional silk ecru stripes',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Editions MR Saint Germain',
    image: require('../../assets/germain.png'),
    subtitle: 'Men only',
    address: '9 rue Madame, 75006 Paris',
    opened: 'Tuesday to Friday: 11AM - 2PM & 3PM - 7:30PM\nSaturday: 10AM - 7:30PM',
    description: 'At the forefront of the current French menswear revival, this label now has Left and Right Bank outlets, with this stylish store in a converted bank. Despite the name, it is actually styled by two men, who refresh classic tailoring, sometimes a striped shirt or navy blazer, sometimes a floral dandy look or fleece jacket. It has quickly gained a reputation for the quality of its fabrics, with fine cotton shirts, pure wool jackets, and a large range of knitwear. This branch also offers a made to measure service',
    price: 'mid-high',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'AMI',
    image: require('../../assets/ami.png'),
    subtitle: 'Men only',
    address: '14 rue d’Alger, 75001 Paris',
    opened: 'Tuesday - Saturday 11AM - 7:30PM\nSunday 1PM - 7PM',
    description: 'Founded in 2011 in Paris, AMI offers a smart, comprehensive wardrobe of both casual and chic pieces. AMI as a friend, as authenticity, sincerity, always with a positive and smiling message. In 2013, Alexandre was the first male designer to win the prestigious ANDAM prize',
    price: 'mid-high',
    price_tag: '€€',
    reservation: false,
  },
];

