export default [
  {
    title: 'Centre Commercial',
    image: require('../../assets/commercial.png'),
    subtitle: 'Multibrand - Women & Men & Lifestyle',
    address: '2 rue de Marseille, 75010 Paris',
    opened: 'Monday 1PM - 7:30PM\nTuesday - Saturday 10:30AM - 8PM\nSunday 2PM - 7PM',
    description: 'Centre Commercial offers labels made in France, Great Britain and Denmark and houses second-hand bicycles, vintage furniture and art works. It is a collective space, uniting local, social and environmental initiatives',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Archive 18-20',
    image: require('../../assets/archive.png'),
    subtitle: 'Multibrand - Women & Men & Lifestyle',
    address: '20 Rue des Archives, 75004 Paris',
    opened: 'Monday - Sunday 11AM - 7:30PM',
    description: 'Archive 18-20 has been initiated by the founder of the parisian menswear brand Ly Adams, as an extension of the brand’s universe. Open since September 2015, the store is located in the heart of the trendy neighborhood of Le Marais. Under the vast glass roof of this 450 sqm space, a concept store, an art gallery, a book store and a restaurant happily cohabit',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Merci',
    image: require('../../assets/merci.png'),
    subtitle: 'Multibrand - Women & Men & Lifestyle',
    address: '111, Bd. Beaumarchais, 75003 Paris',
    opened: 'Monday - Saturday 10AM - 7PM',
    description: 'Merci was opened in march 2009 in a 1500sq meter old wallpaper factory and is one of the most eclectic general stores of Paris. Located in the heart of the trendy neighbourhood of Le Haut Marais, Merci features a great variety of goods, from interior design to fashion, two cafés and one restaurant',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'L’Exception',
    image: require('../../assets/exception.png'),
    subtitle: 'Multibrand - Women & men & lifestyle',
    address: '24 rue Berger, 75001 Paris',
    opened: 'Monday to Saturday 10AM - 8PM\nSunday 11AM - 7PM',
    description: 'You will find in the flagship store a selection of the best french brands and products as well as exclusive pieces and special events. You will also be able to enjoy some of the finest food and coffee in Paris with our partners La Petite Table, Coutume Cafe and Gontran Cherrier',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'FrenchTrotters',
    image: require('../../assets/frenchtrotters.png'),
    subtitle: 'Multibrand - Women & men & lifestyle',
    address: '128, Rue Vieille du Temple, 75003 Paris',
    opened: 'Monday 2:30PM - 7:30PM\nTuesday - Saturday 11:30AM - 8PM\nSunday 2PM - 7PM',
    description: 'FrenchTrotters has set its store in the heart of the upper Marais - rue Vieille du Temple -, offering a unique destination in the city. The carefully curated selection includes the likes of Nigel Cabourn, Comme des Garçons, Woolrich Woolen Mills, Visvim, Engineered Garments, Gitman Vintage, Band of Outsiders, Alden, Yuketen, among others. The store is also hosting FrenchTrotters in-house collection, entirely crafted in Paris, alongside a handful of collaborative products and exclusive items',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
];
