export default [
  {
    title: 'Apple Opera',
    image: require('../../assets/apple.png'),
    subtitle: 'High-Tech Heaven',
    address: '12 Rue Halévy, 75009 Paris',
    opened: 'Monday - Saturday  9:30AM - 8PM\nSunday 11AM - 6PM',
    description: 'Apple\'s Parisian Flagstore',
    price: 'Depending on the products',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Devialet',
    image: require('../../assets/devialet.png'),
    subtitle: 'High-Tech Heaven',
    address: '126 rue Réaumur, 75002 Paris',
    opened: 'Monday - Saturday 10AM - 7PM',
    description: 'Devialet\'s flagship is located in the heart of Paris, in a unique building that took part in the 1898 facades\' contest. A unique place where acoustic excellency is the essence. Devialet is he world’s most critically acclaimed start-up for the excellence of its innovations in sound technologies',
    price: 'Depending on the products',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Parrot',
    image: require('../../assets/parrot.png'),
    subtitle: 'High-Tech Heaven',
    address: '30 - 34 Rue du 4 Septembre, 75002 Paris',
    opened: 'Monday - Saturday 10AM - 7PM',
    description: 'This is the true showcase of an inspired brand. Curated and designed by Philippe Starck, the Parrot store is a modern space which highlights the deeply technological products designed by the French company. \"People often ask me what is the link between A.R. Drone and hand-free systems for the car. The Parrot store will exhibit the whole of our achievements: high-tech objects designed for Smartphones\" - Henri Seydoux, founder and CEO of Parrot',
    price: 'Depending on the products',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'RetroFutur',
    image: require('../../assets/retrofutur.png'),
    subtitle: 'High-Tech Heaven',
    address: '55 Quai de Valmy, 75010 Paris',
    opened: 'Sunday - Monday 1:30PM - 7PM\nWednesday - Saturday 10:30AM - 8PM',
    description: 'Great music store with very nice and friendly staff with an amazing selection of high quality music equipment from amp to headphones including Bang and Olufsen, Sonos etc...',
    price: 'Depending on the products',
    price_tag: '€€',
    reservation: false,
  },
  {
    title: 'Fnac',
    image: require('../../assets/fnac.png'),
    subtitle: 'High-Tech Heaven',
    address: '74, avenue des Champs-Elysées - 75008 Paris',
    opened: 'Monday - Saturday 10AM - 11:45PM Sunday 12:PM - 11:45PM',
    description: 'One of Europe\'s largest Electronic stores that offers the best of a range of cultural and entertainment goods and innovative consumer electronics',
    price: 'Depending on brands',
    price_tag: '€€',
    reservation: false,
  },
];



